# Use this file to create a conda environment for developing this Python
# package. See the comments below for some useful commands for working with
# this environment.
#
# Create the environment ....... conda env create --file environment.yml
# Activate the environment ..... conda activate genja
# Deactivate the environment ... conda deactivate
# Remove the environment ....... conda env remove --name genja

name: genja

dependencies:
  - python
  - beautifulsoup4
  - build
  - ipython
  - jinja2
  - markdown
  - pytest
  - twine
  - pip
  - pip:
    - ruff
    - livereload
    - ipdb
    - --editable .
